CREATE Database School_DB;

USE School_db;

Create table STUDENT
(STUD_ID integer PRIMARY KEY,
FIRTST_NAME VARCHAR(50) NOT NULL,
LAST_NAME VARCHAR(50) NOT NULL,
DOB DATE NOT NULL,
CITY VARCHAR(50) NOT NULL,
STATE VARCHAR(50)NOT NULL,
INTR_ID VARCHAR(6) NOT NULL,
PHONE VARCHAR(10) NOT NULL,
GENDER VARCHAR(1) NOT NULL);


CREATE TABLE INSTRUCTOR
(INSTR_ID VARCHAR PRIMARY KEY,
FIRST_NAME VARCHAR(50) NOT NULL,
LAST_NAME VARCHAR(50) NOT NULL,
COURSE_ID VARCHAR(6) NOT NULL);

CREATE TABLE COURSE
(COURSE_ID VARCHAR PRIMARY KEY,
COURSE_NAME VARCHAR(20) NOT NULL,
COURSE_CREDIT INTEGER NOT NULL,
CLASS_SIZE INTEGER NULL);


CREATE TABLE STUDENT_LEADERSHIP 
(STUD_EXEC_ID INTEGER PRIMARY KEY,
FIRST_NAME VARCHAR(50) NOT NULL,
LAST_NAME VARCHAR(50) NOT NULL,
STUD_ID INTEGER NOT NULL,
TITLE VARCHAR(50) NOT NULL);

CREATE TABLE STUDENT_GRADE
(LETTER_GRADE VARCHAR(1) PRIMARY KEY,
SCORE INTEGER NOT NULL);

ALTER TABLE INSTRUCTOR
ADD CONSTRAINT FK_COURSE_COURSE_ID FOREIGN KEY(COURSE_ID)
REFERENCES COURSE_TABLE (COURSE_ID);